### ISSUE TITLE
Too many empty lines

### ISSUE THREAD

**Issue by dertuxmalwieder** [kbarni/wsconvert#3]
*Opinion:* `wsconvert` should not add more empty lines than required.

I wrote a test document in [WordTsar](http://wordtsar.ca):

```
This is a test.
.. a comment
And ^Banother test^B.
```

Result:

```
This is a test.



And **another test**.
```

I *think* that `wsconvert` shouldn't add more than one line break in a row...?

**Comment by kbarni** [comment]
solved in commit 74a5a6d942e0cebe6ecbad41bbc7647673c87daf
